// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizaCaixas.Data;

#nullable disable

namespace OrganizaCaixas.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529230012_CriacaoTabelas")]
    partial class CriacaoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizaCaixas.Data.Entities.CaixaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NomeCaixa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Caixas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 30m,
                            Comprimento = 80m,
                            Largura = 40m,
                            NomeCaixa = "Caixa 1"
                        },
                        new
                        {
                            Id = 2,
                            Altura = 80m,
                            Comprimento = 40m,
                            Largura = 50m,
                            NomeCaixa = "Caixa 2"
                        },
                        new
                        {
                            Id = 3,
                            Altura = 50m,
                            Comprimento = 60m,
                            Largura = 80m,
                            NomeCaixa = "Caixa 3"
                        });
                });

            modelBuilder.Entity("OrganizaCaixas.Data.Entities.PedidoProcessadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoIdOriginal")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoCaixasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidosProcessados");
                });
#pragma warning restore 612, 618
        }
    }
}
